#!/usr/bin/env python3
"""Write src/cp932.h from Python's own cp932 codec.

Every string a CMVS game hands the engine is CP932: the script string pools,
the archive entry names, cmvs.cfg. The glyph rasteriser works in Unicode code
points, so one table has to bridge them, and generating it from the standard
codec is the only way to be sure it is the real mapping rather than a
hand-typed approximation of one.

    python3 tools/gen_cp932.py > src/cp932.h
"""
import sys

LEAD = [(0x81, 0x9f), (0xe0, 0xfc)]
TRAIL_FIRST, TRAIL_LAST = 0x40, 0xfc
SPAN = TRAIL_LAST - TRAIL_FIRST + 1

leads = [b for lo, hi in LEAD for b in range(lo, hi + 1)]

out = sys.stdout
out.write("/* Generated by tools/gen_cp932.py from Python's cp932 codec. Do not edit. */\n")
out.write("#ifndef CMVS_CP932_H\n#define CMVS_CP932_H\n\n")
out.write("#define CMVS_CP932_TRAIL_FIRST 0x%02x\n" % TRAIL_FIRST)
out.write("#define CMVS_CP932_TRAIL_LAST  0x%02x\n" % TRAIL_LAST)
out.write("#define CMVS_CP932_TRAIL_SPAN  %d\n" % SPAN)
out.write("#define CMVS_CP932_ROWS        %d\n\n" % len(leads))
out.write("/* Which lead bytes have a row here, in order. */\n")
out.write("static const unsigned char cmvs_cp932_lead[CMVS_CP932_ROWS] = {\n   ")
for i, lead in enumerate(leads):
    out.write(" 0x%02x," % lead)
    if i % 12 == 11:
        out.write("\n   ")
out.write("\n};\n\n")

out.write("static const unsigned short cmvs_cp932_table[CMVS_CP932_ROWS][CMVS_CP932_TRAIL_SPAN] = {\n")
for lead in leads:
    out.write("    { /* lead 0x%02x */\n       " % lead)
    for i, trail in enumerate(range(TRAIL_FIRST, TRAIL_LAST + 1)):
        try:
            text = bytes((lead, trail)).decode("cp932")
            value = ord(text) if len(text) == 1 else 0
        except UnicodeDecodeError:
            value = 0
        out.write(" 0x%04x," % value)
        if i % 12 == 11:
            out.write("\n       ")
    out.write("\n    },\n")
out.write("};\n\n#endif\n")
